version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # run these when most of our developers don't work
      day: "sunday"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[no-test]"
    labels:
      - "node_modules"
    groups:
      eslint:
        patterns:
          - "eslint*"
      esbuild:
        patterns:
          - "esbuild*"
      patternfly:
        patterns:
          - "@patternfly*"
      react:
        patterns:
          - "react*"
      stylelint:
        patterns:
          - "stylelint*"
      types:
        patterns:
          - "@types*"
          - "types*"
      xterm:
        patterns:
          - "@xterm/*"

    ignore:
      # needs to be done in Cockpit first
      - dependency-name: "@patternfly/*"
        update-types: ["version-update:semver-major"]

      # PF6 doesn't support React 19 yet.
      # https://github.com/patternfly/pf-roadmap/issues/201
      - dependency-name: "*react*"
        update-types: ["version-update:semver-major"]

      # @xterm/addon-canvas is deprecated and requires xterm/xterm 5.x.x
      - dependency-name: "@xterm/*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    labels:
      - "no-test"
    schedule:
      interval: "weekly"
