name: cockpit-lib-update
on:
  schedule:
    - cron: '0 2 * * 4'
  # can be run manually on https://github.com/cockpit-project/cockpit-podman/actions
  workflow_dispatch:
jobs:
  cockpit-lib-update:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y make

      - name: Set up configuration and secrets
        run: |
          printf '[user]\n\tname = Cockpit Project\n\temail=cockpituous@gmail.com\n' > ~/.gitconfig
          echo '${{ secrets.GITHUB_TOKEN }}' > ~/.config/github-token

      - name: Clone repository
        uses: actions/checkout@v6

      - name: Run cockpit-lib-update
        run: |
          make bots
          bots/cockpit-lib-update
